apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - advanced-generic-workspace
  - default-generic-workspace
  - avoidable-admissions
  - diabetic-foot-ulcer-research
  - arcnwc-chi-se419
  - arcnwc-chi-se421
  - vc-sd-workspace
  - lth-data-science-team-workspace
  - neurosurgery-generic-workspace
  - uhmb-generic-workspace